apiVersion: v1
kind: Service
metadata:
  name: k8s-service
  labels:
    app: k8s
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: k8s
    version: v0.0.1
